name: Epam AutoTests Pipeline

on:
  pull_request:
    branches: [ "main", "master" ]
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      browser:
        description: 'Choose browser for UI tests'
        required: true
        default: 'Chrome'
        type: choice
        options:
          - Chrome
          - Firefox
          - Edge

jobs:
  api-tests:
    name: Run API Tests
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Run API Tests
        run: >
          dotnet test ./Tests.API/Tests.API.csproj 
          --logger "trx;LogFileName=api-results.trx" 
          --results-directory ./TestResults

      - name: Upload API Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: ./TestResults/api-results.trx
          retention-days: 7
          
  ui-tests:
    name: Run UI Tests
    runs-on: windows-latest
    env:
      GITHUB_ACTIONS: true 
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Run UI Tests
        run: >
          dotnet test ./Tests.UI/Tests.UI.csproj 
          --logger "trx;LogFileName=ui-results.trx" 
          --results-directory ./TestResults 
          -- 'TestRunParameters.Parameter(name="Browser", value="${{ inputs.browser || 'Chrome' }}")'

      - name: Upload UI Artifacts (Screenshots & Logs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-artifacts
          path: |
            ./TestResults/*.trx
            ./Tests.UI/bin/**/Logs/*.log
            ./Tests.UI/bin/**/Screenshots/*.png
          retention-days: 7